.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. btq_qt test_btq_qt
clean: FORCE
	$(MAKE) -C .. btq_qt_clean test_btq_qt_clean
check: FORCE
	$(MAKE) -C .. test_btq_qt_check
btq-qt btq-qt.exe: FORCE
	 $(MAKE) -C .. btq_qt
apk: FORCE
	$(MAKE) -C .. btq_qt_apk
